import type { Metadata } from "next";
import "./globals.css";
import { Analytics } from '@vercel/analytics/next';
import { ThemeProvider } from "@/components/ui/theme-provider";
import { SpeedInsights } from "@vercel/speed-insights/next"
import NavBar from "@/components/NavBar";
import Footer from "@/components/footer";
import { Providers } from '@/app/provider';
import Script from "next/script";

export const metadata: Metadata = {
  icons: "/favicon.ico",
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <Providers>
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
            >
              <NavBar />
              {children}
              <Footer />
              <SpeedInsights />
              <Analytics />
            </ThemeProvider>
          </Providers>
          <Script src="https://mercury-stg.phonepe.com/web/bundle/checkout.js" 
          strategy="afterInteractive"
          defer
          />
        </body>
      </html>
    </>
  );
}
